### ISSUE TITLE
Migrate to Unsplash API

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#1085]
Unsplash decided to sunset their https://source.unsplash.com domain without any warning so now all image fetching is broken. We'll have to migrate to their API but think that'll get us into API limits. I don't know if the generated urls from Unsplash are long lived. If they are we could maybe save them in the database otherwise we might have to run a scheduled job to refresh them during their TTL.

**Comment by driesvints** [comment]
Tim mentions the old ID's are still relevant: https://x.com/TimVanDijck/status/1795455355981304124

**Comment by tauseefsshah** [comment]
Hi @driesvints Wanted to check if you're working on this issue because I have a working solution

- The unsplash API provides a `get` endpoint that takes the image id and returns [hotlink cdn ](https://unsplash.com/documentation#hotlinking)`urls` (The urls remains constant) 
![image](https://github.com/user-attachments/assets/76e8004d-3768-4cf1-ab83-14aee0684a74)
- These images are [dynamically resizable](https://unsplash.com/documentation#dynamically-resizable-images) so we can just pass the width and height parameters and just like [https://source.unsplash.com/](https://source.unsplash.com/) have our images

**Solution Options**

1. We can get the hotlinked cdn urls by calling the API on all image ids and save the urls in the DB in a new colunm (Then we will never need to call the api's again)
2. Or from the image urls we can download and store these images in the public folder or S3 and store the urls to these images in DB (Now we have the full control and just in case they change their hotlinked image policy, the images will be safe)

**My Queries**

1. How was image id set for an article before? (Didn't find anything in the code, did you remove it?)
2. If we go with the 2nd option should I use `spatie/medialibrary` or just go with the filesystem? (Media library so that images can be resized and it's just convenient)

**Comment by driesvints** [comment]
If the urls remain constant then yeah we can indeed set them in a table column. @joedixon already worked a bit on a command to go over each article here: https://github.com/laravelio/laravel.io/pull/1090

> How was image id set for an article before? (Didn't find anything in the code, did you remove it?)

It's done here: 

https://github.com/laravelio/laravel.io/blob/8e873eb9cb3bfb5b38aeb99a69d68b83aa9408e1/app/Models/Article.php#L109

Or did you mean how it was saved? There's no code for that. I manually copied the identifier and added it to the record in the database. We want to eventually develop an image picker but that's quite a bit of work.

**Comment by tauseefsshah** [comment]
Yes I meant how it was saved. Thank you for the clarification.
I'll work on a PR for this 😄
