### ISSUE TITLE
Experience points

### ISSUE THREAD

**Issue by joedixon** [laravelio/laravel.io#415]
As a user, I should gain experience points when creating threads, replying to threads, having my solution marked as accepted, etc so that I get recognition from the community for my input.

**Comment by driesvints** [comment]
I think we should be a bit smart about this and not just award points for every thread or reply. Because that could lead to spam. But yeah some award system could definitely be nice 👍

**Comment by ryangjchandler** [comment]
One way to get around the attempts at spam might be to only reward XP for the first reply on a thread for example.

**Comment by bhushan** [comment]
This functionality is pretty big. I can make this package open-source if it suites the requirements. Otherwise, I can also contribute to some of the parts of a big chunk. Let me know if it works.. :)

![screencapture-github-bhushan-achievements-package-2021-04-17-04_05_23](https://user-images.githubusercontent.com/43483545/115090441-8399ad80-9f32-11eb-9fef-3db129abdfe3.png)

**Comment by driesvints** [comment]
As I said on Twitter, atm we're not focusing on this part but on other parts of the application. If and when we'll implement this feature we'll need to have a very good think-through first about how we'd like to tackle it before development can begin.
