### ISSUE TITLE
Implement Laravel email verification

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#421]
Atm we're still rolling with our own solution before this was natively in Laravel. Let's see if we can implement the core functionality for this: https://laravel.com/docs/verification

**Comment by pushpak1300** [comment]
Can I work on this? @driesvints

**Comment by driesvints** [comment]
@pushpak1300 go for it

**Comment by pushpak1300** [comment]
@driesvints just wanted to know that currently in the application verification logic is store in the confirmed column but if we want to change it no native laravel we are required email_verified_at column.
Just a question that how we are going to solve that issue because all previous users don't have email_verified_at column in their table.
Can you help me here?

**Comment by driesvints** [comment]
I'm guessing we could require people to verify their email again. Just leaving the column blank will prompt the banner in the app I believe.
