### ISSUE TITLE
Identify slow queries

### ISSUE THREAD

**Issue by driesvints** [laravelio/laravel.io#742]
We should identify slow queries, especially on the forum overview page which seem much slower than the rest of the site. Most likely this is due to lots of queries being performed or lots of relationships being loaded in. Or possible also missing table indexes.

Let's first identify them, add them to this issue and then check how we can improve them.

**Comment by tvbeek** [comment]
## Queries

I see 2 queries in the debugbar that are slower than the rest. (The queries are after #745 because else I didn't got it working, that is why you see more fields in the group by.)

```sql
select count(*) as aggregate from (select `threads`.*,
CASE WHEN COALESCE(MAX(replies.created_at), 0) > threads.created_at
THEN COALESCE(MAX(replies.created_at), 0)
ELSE threads.created_at
END AS latest_creation
from `threads`
left join `replies` on `threads`.`id` = `replies`.`replyable_id` and `replies`.`replyable_type` = 'threads'
group by `threads`.`id`, `threads`.`author_id`, `threads`.`subject`, `threads`.`body`, `threads`.`slug`, `threads`.`created_at`, `threads`.`updated_at`, `threads`.`solution_reply_id`, `threads`.`resolved_by`
) as `aggregate_table`
```

And  
```sql
select `threads`.*,
CASE WHEN COALESCE(MAX(replies.created_at), 0) > threads.created_at
THEN COALESCE(MAX(replies.created_at), 0)
ELSE threads.created_at
END AS latest_creation
from `threads` left join `replies` on `threads`.`id` = `replies`.`replyable_id` and `replies`.`replyable_type` = 'threads' group by `threads`.`id`, `threads`.`author_id`, `threads`.`subject`, `threads`.`body`, `threads`.`slug`, `threads`.`created_at`, `threads`.`updated_at`, `threads`.`solution_reply_id`, `threads`.`resolved_by` order by `latest_creation` desc limit 20 offset 0
```

On my local machine the first take around 12ms and the second around 9ms. (The other 9 queries are around 1ms and the full request is 800 ms.

 I suspected an index on the created_by for the replies and threads could help but I didn't see any real difference. Maybe someone else see a way to speed this up.

## Models

There is a total of 389 models loaded:  
![image](https://user-images.githubusercontent.com/2026498/142053930-1b5036b5-b381-4006-9bcc-a1ca4de38c5b.png)

Some points that I see that can help in the load time:
* The replies are loaded while we only show the number of replies
* The likes are loaded while we only show the number of likes
* I'm not sure what the reason is to load this amount of users.

**Comment by joedixon** [comment]
@tvbeek thanks, this is an incredibly helpful audit.

I had found the same with the forum overview query. I'm thinking that instead, we keep a timestamp on the `threads` table that gets updated every time a reply is created and sort by that. I don't want to use `updated_at` field as I still want that to reference the thread itself.

I didn't know about the models being hydrated only for counts so will look at that too.

**Comment by driesvints** [comment]
Forum overview is now 🚀  

Thanks @tvbeek & @joedixon!
